version: '3.8'
services:
  redis:
    restart: unless-stopped

  db:
    restart: unless-stopped

  fluentd:
    restart: unless-stopped

  app:
    image: task3
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=1

  proxy:
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
